-- liquibase formatted sql

-- changeset cerrato:1
CREATE TABLE media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type ENUM('SERIES', 'MOVIE') NOT NULL, CONSTRAINT media_key PRIMARY KEY (id))
-- rollback drop table media

-- changeset cerrato:2
CREATE TABLE spaceship (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, media INT NOT NULL, CONSTRAINT fk_media FOREIGN KEY (media) REFERENCES media(id), CONSTRAINT spaceship_key PRIMARY KEY (id));
-- rollback drop table spaceship